version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

  php-fpm:
    image: php:7.2.2-apache
    volumes:
      - "./php:/var/www/html"
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${PHP_PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    stdin_open: true
    tty: true
    networks:
      - proxy

networks:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
