version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default
    volumes:
      - "./db:/var/lib/mysql"

  php:
    build: .
    volumes:
      - "./php:/var/www/html"
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: ${PF_SSL_DOMAIN}
      VIRTUAL_PORT: ${PHP_PORT}
      LETSENCRYPT_HOST: ${PF_SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    stdin_open: true
    tty: true
    networks:
      - proxy
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
      VIRTUAL_HOST: ${PMA_SSL_DOMAIN}
      VIRTUAL_PORT: ${PMA_PORT}
      LETSENCRYPT_HOST: ${PMA_SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
