version: "3."

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default
    restart: always
    volumes:
      - "./db:/var/lib/mysql"

  php:
    build: .
    container_name: php_server
    volumes:
      - "./php:/var/www/html"
      - "${DOCKER_STATIC_HOSTING}:${DOCKER_STATIC_HOSTING}:rw"
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      STATIC_FILE_HOSTING: ${DOCKER_STATIC_HOSTING}
      STATIC_FILE_HOSTING_URL: ${DOCKER_STATIC_HOSTING_URL}
    stdin_open: true
    tty: true
    restart: always
    networks:
      - https
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
    restart: always
    networks:
      - https
      - default

networks:
  https:
    name: ${HTTPS_NETWORK}
    external: true      
